In [18]:
from texture.TextureClassifier import TextureClassifier
import os
import logging

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
data_dir = '/home/jiaxuzhu/data/all_patches'
p_labels = ['5N', '7n', '7N', '12N', 'Gr', 'LVe', 'Pn', 'SuVe', 'VLL', 'BackG']

In [19]:
model_dir = '/home/jiaxuzhu/developer/CSD395/model/inception-bn'
prefix = 'Inception_BN'
n_iter = 39

tc = TextureClassifier(model_dir, prefix, n_iter, 10)
tc.mx_init(data_dir, 128)
tc.mx_training(6, 0.001, 128, os.path.join(model_dir, 'inception-stage1'))

INFO:root:Start training with [gpu(0)]
INFO:root:Epoch[0] Batch [30]	Speed: 125.83 samples/sec	Train-accuracy=0.494792
INFO:root:Epoch[0] Batch [60]	Speed: 119.13 samples/sec	Train-accuracy=0.614583
INFO:root:Epoch[0] Batch [90]	Speed: 111.10 samples/sec	Train-accuracy=0.681684
INFO:root:Epoch[0] Batch [120]	Speed: 112.95 samples/sec	Train-accuracy=0.723828
INFO:root:Epoch[0] Batch [150]	Speed: 110.09 samples/sec	Train-accuracy=0.749844
INFO:root:Epoch[0] Batch [180]	Speed: 111.53 samples/sec	Train-accuracy=0.771181
INFO:root:Epoch[0] Batch [210]	Speed: 111.51 samples/sec	Train-accuracy=0.788690
INFO:root:Epoch[0] Batch [240]	Speed: 111.65 samples/sec	Train-accuracy=0.801693
INFO:root:Epoch[0] Batch [270]	Speed: 111.23 samples/sec	Train-accuracy=0.813252
INFO:root:Epoch[0] Train-accuracy=0.819309
INFO:root:Epoch[0] Time cost=325.958
INFO:root:Epoch[0] Validation-accuracy=0.837891
INFO:root:Saved checkpoint to "/home/jiaxuzhu/developer/CSD395/model/inception-bn/inception-stage1-0001.par

In [26]:
model_dir = '/home/jiaxuzhu/developer/CSD395/model/inception-bn'
prefix = 'inception-stage1'
n_iter = 6

tc = TextureClassifier(model_dir, prefix, n_iter, 10)
tc.mx_init(data_dir, 128)

prob = tc.init_model.predict(tc.iter['test'])
print prob.shape


(151925, 10)


In [39]:
import numpy as np

y_batch = []
tc.iter['test'].reset()

py = np.argmax(prob, axis=1).flatten()
confusion = np.zeros((tc.n_class, tc.n_class)).astype(int)
count = 0
with open(os.path.join(data_dir, 'test.lst'), 'r') as test_lst:
    idx = 0
    for line in test_lst.readlines():
        label = int(line.split('\t')[1])
        if label == py[idx]:
            count += 1
        confusion[label, py[idx]] += 1
        idx += 1
print 'testing accuracy is %.4f' % (float(count)/idx)
print confusion

testing accuracy is 0.9263
[[   543      0      0      0      0      0      0      0      0      6]
 [     2    476      0      0      0      2      0      0      0     23]
 [     0      0   1106      0      0      3      0      0      0      9]
 [     0      0      2    493      0      0      1      0      0     11]
 [     0      0      0      0    292      0      0      0      0      6]
 [     0      0      0      0      0    657      0      0      0      5]
 [     0      0      0      0      0      0   3089      0      1     23]
 [     1      0      0      0      0      0      0    251      0      0]
 [     1      0      1      0      0      0      1      1    575     11]
 [   917    501   1277    786    546   2554   3351    324    834 133243]]


In [41]:
import numpy as np

y_batch = []
tc.iter['test'].reset()

py = np.argsort(-prob, axis=1)
confusion = np.zeros((tc.n_class, tc.n_class)).astype(int)
count = 0
with open(os.path.join(data_dir, 'test.lst'), 'r') as test_lst:
    idx = 0
    for line in test_lst.readlines():
        label = int(line.split('\t')[1])
        if label == py[idx][0] or label == py[idx][1]:
            count += 1
            confusion[label, label] += 1
        else:
            confusion[label, py[idx][0]] += 1
        idx += 1
print 'top 2 testing accuracy is %.4f' % (float(count)/idx)
print confusion

top 2 testing accuracy is 0.9913
[[  1   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0   1]
 [  0   0   0   1   0   0   1   0   0   1]
 [  0   0   0   0   1   0   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0]
 [  1   0   0   0   0   0   0   0   1   0]
 [171  21 368 102  14 263 127  76 175   1]]
